### ISSUE TITLE
swiftmailer is abandoned

### ISSUE THREAD

**Issue by flwyd** [burningmantech/ranger-clubhouse-api#1055]
Running `composer install` reports that `Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.`  The [swiftmailer README](https://github.com/swiftmailer/swiftmailer) says that it is unmaintained as of late 2021 and urges users to upgrade to [Symfony Mailer](https://symfony.com/doc/current/mailer.html).  A [blog post](https://symfony.com/blog/the-end-of-swiftmailer) claims that the migration is easy "as the concepts are the same" but doesn't provide any details about the migration, like changes to classnames.

**Comment by mikeburg** [comment]
The backend has been upgraded to Laravel 9 which only includes symfony/mailer. Closing this out.
