### ISSUE TITLE
Position Sanity Checker needs to add "Gerlach Patrol - Green Dot" where appropriate.

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-api#109]
The new position "Gerlach Patrol - Green Dot" has been created for 2019 to support the split nature of a GP shift.  A shift will consist of a dirt ranger, and a green dot.

The checker needs to add the new position to anyone who is an existing Green Dot.

**Comment by wsanchez** [comment]
done?

**Comment by flwyd** [comment]
Pretty sure I did this.
