### ISSUE TITLE
Figure out when to deal with pending database migrations.

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-api#11]
Laravel, the web framework used for the backend, supports database migrations. When the backend is being deployed, the outstanding migrations should be executed.

The command to do this is `php artisan migrate`. 

Migration errors should stop the build task, and report the problems.  A migration can be rolled back by the command `php artisan migrate:rollback'

See the laravel documentation for more information:
https://laravel.com/docs/5.7/migrations

**Comment by wsanchez** [comment]
Cool, thanks for the info; this was on my list of things to ask about.

**Comment by wsanchez** [comment]
Required for #2

**Comment by flwyd** [comment]
We've got an additional complication that Ye Olde Clubbe House also cares about the same tables.

Maybe the solution is to ensure the php artisan command in neoclubhouse runs before the legacy clubhouse can be pushed, but I'm not sure if there's a straightforward way for computers to enforce that rule.

Are the migrations smart enough to be idempotent, so a schema push doesn't fail if some tables already look the way they're supposed to?

**Comment by wsanchez** [comment]
So, question.  Does CH2 use the same DB as CH1, or a separate one?

I've been assuming the latter, in which case: I'd like it if (a) the current real schema in production were put into the CH2 code somewhere and all migrations from that are managed by CH2.  Meaning that one could start CH2 with an empty database and end up with a correct schema.  Is that feasible?

As to Stonebeard's question, I think we may need a phone call to talk about deployment automation options…

**Comment by mikeburg** [comment]
@wsanchez writes:
> Meaning that one could start CH2 with an empty database and end up with a correct schema. Is that feasible?

Its feasible now thanks to this commit: https://github.com/burningmantech/ranger-clubhouse-api/commit/6ee3cf17d008105266b9ba817baefb5c8ce8f5db

**Comment by wsanchez** [comment]
Woot

**Comment by wsanchez** [comment]
OK now I need to figure out how to tell AWS ECS to run a task prior to deploying a new version.

**Comment by wsanchez** [comment]
References:
 * [How To Run Migrations on AWS ECS and Other One off Tasks ](https://medium.com/boltops/how-to-run-migrations-on-aws-ecs-and-other-one-off-tasks-ebc3e54702c5)

**Comment by wsanchez** [comment]
According to this:

https://engineering.instawork.com/elegant-database-migrations-on-ecs-74f3487da99f

...the clever way to do this is to do the migration and make sure it completes before your app starts telling the load balancer that it is healthy.

We can do that by not starting the web server until migration completes.  The question is, then, if multiple containers try to migrate at the same time, is that a problem?

**Comment by wsanchez** [comment]
OK, and here

https://laraveldaily.com/how-to-deploy-laravel-projects-to-live-server-the-ultimate-guide/

...the author suggests that one run `php artisan down`, then migrate, then `php artisan up`.  `php artisan down` will cause the server to emit 503 status code responses, which is great for our purposes.

The [`start-nginx`](https://github.com/burningmantech/ranger-clubhouse-api/blob/master/docker/start-nginx) script already does some stuff before starting the server, so this should be straightforward.

**Comment by wsanchez** [comment]
Actually, no need to both with down/up; just migrate before starting.
