### ISSUE TITLE
Enhancement Request: Paid Driver Report

### ISSUE THREAD

**Issue by vought** [burningmantech/ranger-clubhouse-api#1196]
As a Ranger Department Manager, I'd like to be able to easily see which Rangers have:

-Signed the MVR and have been cleared to operate a motor vehicle at Burning Man in the current event year.
-Have been trained to drive the tow truck in any previous year.
-Have driven (not menteed) a shift in a previous event year.
-Have already signed up for a Captain Hook shift or training in the current event year.

A report of this type should generate a list of drivers who have driven in the past, are trained or will be trained in the current event year, and who have MVR authorization. This is the list of people who may be paid for their work in these shifts.

If this implementation exceeds 1.5 hours per event year, it's not economical compared to using the clubhouse and a spreadsheet.

**Comment by mikeburg** [comment]
After having a discussion with Po-Boy, this report is not worth pursuing at this time. The requested report is not deemed critical, only a nice-to-have one, and the driver count is very low: 12 in 2022, 13 in 2023.
