### ISSUE TITLE
Notify client of server relocation

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-api#12]
Ideally, the tech team would like to run the Clubhouse locally on playa for the event. In the past, it was a relatively simple series of steps involving moving the database and Clubhouse code to a local machine,  and configure the cloud web server to redirect to the on-playa server. Anyone currently logged into the cloud-based Clubhouse when the Clubhouse was automatically relocated to the new location.

With Clubhouse 2.0, things become a little trickery since the frontend may be cached in the browser, and the frontend has to handle the redirect itself instead of relying of the browser to  automatically do it. (page redirect when a new page is loaded in a static website vs api redirect in a javascript application.)

A fresh user (not logged in, frontend not previously cached in the browser) visiting the relocated Clubhouse should not experience an issue. If they hit, ranger-clubhouse.burningman.org, the cloud web server will issue a redirect to ranger-clubhouse.nv.burningman.org. The frontend is loaded from the playa, the frontend starts calling the playa-based backend, and all is well.

For an existing user (logged in, or frontend cached in the browser), there will be an issue with the frontend trying to talk with the backend that was relocated to a new end point (i.e. moved from the cloud to the playa.) The frontend calls the cloud-based backend, and the cloud responds with "hey, I've been relocated to the playa".

The problem with the frontend simply updating the API backend location is CORS will be triggered. CORS is a security check performed by the browser when a javascript application loaded from domain tries issuing ajax/API requests to another domain.  The browser will first call the server with the http verb OPTIONS and the url - this asks the server if it's okay to proceed with the cross domain request. If the server responds with an approval, the browser will issue the real request. One request ends up being two requests.

One solution is have the frozen backend report a HTTP status code indicating the server was relocated with the new frontend url - not backend  location - in the response. The frontend would force a reload of the page from the new frontend location.  The frontend and backend domains would be the same at that point and CORS avoided.

The solution should be fairly trivial to implement. The backend would have a flag indicating relocation, and all API requests would respond with the relocation status. A Laravel middleware bit code inserted in the request stack could be used to implement this.

On the frontend,  most API calls exceptions are already handled by one common method handleErrorResponse in app/services/house.js. The method could check to see if this was an relocation respond and cause the frontend application to be loaded from the new location.

(I need to verify this but I believe using any of the 30X redirection HTTP statuses would not work.. the browser would handle the redirection automatically instead of hand the response to the application. I vote for using 418 - a non standard code the browser would pass to the application and the Ember framework would treat as an exception. Also, 418 is the official "I'm a teapot" response.)

**Comment by wsanchez** [comment]
nah
