### ISSUE TITLE
Periodically update the photo cache.

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-clubhouse-api#134]
Periodically update the photo cache.

@mikeburg currently has this running on an external host.

This should be done as a Laravel task, so we're blocked on #17.

**Comment by wsanchez** [comment]
This may end up obsoleted by the new photo thingo?

**Comment by mikeburg** [comment]
Photo management was implemented directly in the Clubhouse -- syncing with an external service has been obsoleted.
