### ISSUE TITLE
Cache composer build stage image in Travis

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-clubhouse-api#15]
Running composer take a lot of time, and if we don't change our dependencies, it's not necessary.

I think we should be able to cache the image generated by the composer build stage and skip that work on most builds.

**Comment by mikeburg** [comment]
How does the cache get invalidated if a package needs to be versioned bumped, or a new package is added to composer.json?

**Comment by wsanchez** [comment]
If you look at [Dockerfile](https://github.com/burningmantech/ranger-clubhouse-api/blob/master/Dockerfile), my understanding is that changes in any of the inputs (`FROM` or `COPY` commands in our case) will cause a rebuild.

There's probably some stuff being copied in that build phase that don't effect Composer, and perhaps should be done in a new separate phase.

**Comment by wsanchez** [comment]
ref: https://github.com/seatgeek/docker-build-cacher
