### ISSUE TITLE
AWSify the Clubhouse API service

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-clubhouse-api#2]
https://docs.travis-ci.com/user/deployment/codedeploy/

**Comment by wsanchez** [comment]
[Use AWS CodeDeploy to Implement Blue/Green Deployments for AWS Fargate and Amazon ECS ](https://aws.amazon.com/blogs/devops/use-aws-codedeploy-to-implement-blue-green-deployments-for-aws-fargate-and-amazon-ecs/)

**Comment by wsanchez** [comment]
OK so CodeDeploy documentation is a Hot Mess™, and I'm bailing out.

New plan is to simply push the built docker image into ECR and have CodePipeline push to staging and production.

That is roughy what we do with Clubhouse classic, except that the docker image is built in CodePipeline as well.

**Comment by wsanchez** [comment]
We are now pushing images to AWS:
https://travis-ci.com/burningmantech/ranger-clubhouse-api/builds/99841147

I've confirmed that this is appearing in ECR.

Next step is having that cause a deploy via CodePipeline.

**Comment by wsanchez** [comment]
OK we're in production.

@mikeburg: can you verify that it's sane-ish?

**Comment by wsanchez** [comment]
Correction: it's in staging

**Comment by mikeburg** [comment]
We have liftoff!

![image](https://user-images.githubusercontent.com/1523824/52605311-1acebc00-2e23-11e9-9b07-596929b4e2e0.png)

The OPTIONS request are happening because the frontend was loaded from a  different domain than the backend. (localhost versus ranger-clubhouse-staging)

**Comment by wsanchez** [comment]
OK Travis is now building the image, then testing it, then deploying to AWS, which means uploading a new docker image and reconfiguring the service to use it:

https://travis-ci.com/burningmantech/ranger-clubhouse-api/builds/100716949

I've verified that each successful run is, in fact, creating a new task definition with the new tagged image and is also updating the service to use the new task definition.  The updated service is launching new tasks, which eventually replace the old ones.

This looks good.
