### ISSUE TITLE
Bulk Upload Access Documents assumes SourceYear and expiryYear

### ISSUE THREAD

**Issue by techxorcist** [burningmantech/ranger-clubhouse-api#414]
When bulk uploading Access Documents, only handle and type of access document can be specified. The sourceYear and expiryYear are assumed to be current_year() - 1 and current_year() + 3, respectively. Ticketing team needs to add back credentials that are claimed but not used and it would be useful to be able to override the defaults for sourceYear and expiryYear with additional fields in the bulk upload.

**Comment by srabraham** [comment]
@techxorcist is this still a desirable feature for the ticketing team? I figured I'd check in with you before actually trying to implement this, since it's been 2.5 years (a whole pandemic of time!) since the issue was filed.

**Comment by techxorcist** [comment]
@srabraham Thanks for checking in and all your work on the Clubhouse. Adding back these claimed but unused credentials is still a thing we do each cycle (and have yet to do this cycle) so being able to specify sourceYear and expiryYear in the upload would be handy.

**Comment by srabraham** [comment]
Thanks! I see that there's already an optional field for Create Access Document uploads, and we're effectively being asked for another two optional fields. That's tricky to do with reasonable UX. @mikeburg: I'm inclined to make all the columns required but optionally empty, i.e. change the documentation from

Line format: callsign,type[,wap date]

to something like

Line format: callsign,type,source date*,expiry date*,wap date*
(fields marked * have reasonable defaults and may be left empty)

My even more preferred approach would be to require the user to include a header, so that fields can be selected at will. That would be inconsistent with other actions though

![image](https://user-images.githubusercontent.com/23407555/203329962-c690fff1-e77c-424e-b89e-09a6d26df91d.png)

**Comment by mikeburg** [comment]
The help format text should definitely be updated. However, WAPs, Significant Other WAPs, and Vehicle Passes are a single-year and single-use item. The items are only ever issued in the year to be used, and expire at the end of the event.  The WAPs & VPs cannot be banked. Long story short, the source year and expiry date parameters should throw an error if present for those types.

Currently, only the Reduced-Price Tickets and Staff Credentials may have a source year and expiry date. 

Also to note about the expiry date -- this will be a year, not a full date. Everything is assumed to have a September 15th  YYYY expiry date.

**Comment by srabraham** [comment]
OK, thanks for that extra context. I'll go ahead with the approach I suggested above then (with the validation you mention), unless you're asking for something different. e.g. of I-think-valid input below

```
# callsign,type,source year*,expiry year*,wap date*
bob,wap,,,2023-08-20
cat,cred,,,
dog,rpt,2017,2022,
```

**Comment by mikeburg** [comment]
> # callsign,type,source year*,expiry year*,wap date*
> bob,wap,,,2023-08-20
> cat,cred,,,
> dog,rpt,2017,2022,

The above is going to be confusing, particularly  the WAP format. Keep the existing line format for the WAPs yet enhance the RPT/SC types. More like this:

```
# For WAPs - callsign,type,wap date
hubcap,wap,2023-08-20
# For a Staff Credential with the defaults
hubcap,cred
# For a RPT with a source year & expiry year
hubcap,rpt,2017,2022
```

**Comment by srabraham** [comment]
An alternative would be to do separate actions altogether for cred/rpt/gift as opposed to vp/wap. If it's sufficiently complicated that it doesn't work well as a single CSV, that seems like a sign to break things up

**Comment by mikeburg** [comment]
Lets consider breaking up the actions later. Right now, the goal is to add a source year and expiry date to the tickets.

**Comment by mikeburg** [comment]
Some additional context here - The uploader is used three different ways. 1) Manual entry, 2) upload thru a CSV file, or 3) copy-n-paste from either a document or spreadsheets. In many cases an upload will  consist of a single type (ticket, wap or vp). In a few case the types will be mixed. The later is usually one offs and done after the main uploads happens.

**Comment by srabraham** [comment]
OK, works for me. Thanks for the context

**Comment by srabraham** [comment]
@techxorcist this is now merged. Hopefully the documentation on the bulk upload page will be good enough, and also I've tightened up validation so that you'll get good error messages, but here's some sample input anyway:

```
# WAP (access date is optional)
hubcap,wap
hubcap,wap,2023-08-20

# RPT (no access date, optional source and expiry year)
hubcap,rpt
hubcap,rpt,2015,2019

# Staff cred (optional access date, source year, and expiry year)
# note that if you want to set source and expiry year, you must set an access date or have an empty spot for it (",,")
hubcap,cred
hubcap,cred,2023-08-20
hubcap,cred,,2015,2019
hubcap,cred,2023-08-20,2015,2019
```
