### ISSUE TITLE
Run unit tests in CI.

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-clubhouse-api#7]
We should run the unit tests in CI.

**Comment by wsanchez** [comment]
@mikeburg I'll need a clue dump on how to run the unit tests.  :-)

**Comment by mikeburg** [comment]
I'll give you a clue when I get a clue myself on how to do that.

**Comment by mikeburg** [comment]
A clue has been found, and some unit tests!

61 unit tests exist which cover the Authentication, Person, and Schedule controllers. More to follow.

Add to .travis.yml :
```
before_script:
 .... 
  - cp .env.testing .env
  - mysql -e 'create database rangers-test;'
....

script: ./vendor/bin/phpunit
```

A successful phpunit run will look like:

```
PHPUnit 7.5.2 by Sebastian Bergmann and contributors.

.............................................................     61 / 61 (100%)

Time: 2.61 seconds, Memory: 42.00MB

OK (61 tests, 158 assertions)
```
An exit status of 0 indicates success, non-zero a failure.

**Comment by mikeburg** [comment]
This is running! Woot! Closing this issue.

**Comment by wsanchez** [comment]
Stand by, still working on it
